# Site settings
title: nowgoant
email: 631359926@qq.com
description: blog Site
baseurl:
url:
twitter_username:
github_username:  nowgoant

# Build settings
markdown: kramdown
highlighter: pygments
encoding: utf-8